---
galaxy_info:
  description: "Install and configure Mailcrab on Kubernetes using the official Helm chart"
  role_name: "mailcrab"
  author: "Clément Hubert"

  license: MPL-2.0

  min_ansible_version: "2.17"

  galaxy_tags:
    - "kubernetes"
    - "mail"
    - "mailhog"
    - "mailcrab"

dependencies: []
