---
- name: "Create clamav namespace"
  kubernetes.core.k8s:
    name: "{{ clamav_namespace }}"
    api_version: "v1"
    kind: "Namespace"
    state: "present"

- name: "Add clamav helm repo"
  kubernetes.core.helm_repository:
    name: "{{ clamav_helm_repo_name }}"
    repo_url: "{{ clamav_helm_repo_url }}"

- name: "Install clamav helm package"
  kubernetes.core.helm:
    name: "{{ clamav_deployment_name }}"
    namespace: "{{ clamav_namespace }}"
    state: "present"
    chart_ref: "{{ clamav_helm_chart_ref }}"
    chart_version: "{{ clamav_helm_version }}"
    update_repo_cache: true
    values: "{{ lookup('ansible.builtin.template', 'clamav_helm_values.yml.j2') | from_yaml }}"
