---
- name: "Include setup when enabled"
  ansible.builtin.include_tasks: "setup.yml"
  when: kargo_enabled
  tags:
    - "kargo"
    - "install"

- name: "Include cleanup when disabled"
  ansible.builtin.include_tasks: "cleanup.yml"
  when: not kargo_enabled
  tags:
    - "kargo"
    - "uninstall"
