---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: "Wait for 'gatus' namespace to be active."
      kubernetes.core.k8s_info:
        kind: Namespace
        name: "gatus"
      register: namespace_gatus
      until:
        - namespace_gatus.resources | length > 0
        - namespace_gatus.resources[0].status.phase == "Active"
      retries: 30
      delay: 5

    - name: "Assert that 'gatus' namespace is active."
      ansible.builtin.assert:
        that:
          - namespace_gatus.resources | length > 0
          - namespace_gatus.resources[0].status.phase == "Active"
        fail_msg: "Namespace 'gatus' is not active."

    - name: "Wait for 'gatus' Deployment to be deployed."
      kubernetes.core.k8s_info:
        kind: "Deployment"
        name: "gatus"
        namespace: "gatus"
      register: gatus_deployment
      until:
        - gatus_deployment.resources | length > 0
        - gatus_deployment.resources[0].status.readyReplicas | default(0) >= 1
      retries: 30
      delay: 5

    - name: "Assert that 'gatus' Deployment is deployed."
      ansible.builtin.assert:
        that:
          - gatus_deployment.resources | length > 0
          - gatus_deployment.resources[0].status.readyReplicas | default(0) >= 1
        fail_msg: "Deployment 'gatus' is not deployed with ready replicas."
