---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: "Wait for 'mailcrab' namespace to be removed."
      kubernetes.core.k8s_info:
        kind: Namespace
        name: "mailcrab"
      register: namespace_mailcrab
      until: namespace_mailcrab.resources | length == 0
      retries: 30
      delay: 5
      changed_when: false

    - name: "Assert that 'mailcrab' namespace is removed."
      ansible.builtin.assert:
        that: namespace_mailcrab.resources | length == 0
        fail_msg: "Namespace 'mailcrab' is still present."

    - name: "Wait for 'mailcrab' basic auth secret to be removed."
      kubernetes.core.k8s_info:
        kind: "Secret"
        name: "mailcrab-basic-auth-secret"
        namespace: "mailcrab"
      register: mailcrab_basic_auth_secret
      until: mailcrab_basic_auth_secret.resources | length == 0
      retries: 30
      delay: 5

    - name: "Assert that 'mailcrab' basic auth secret is removed."
      ansible.builtin.assert:
        that: mailcrab_basic_auth_secret.resources | length == 0
        fail_msg: "Secret 'mailcrab-basic-auth-secret' is still present."
