---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    cloud_provider: "{{ lookup('env', 'DEVENV_DOTFILE') }}/bin/cloud-provider-kind"
    cert_manager_acme_production_enabled: false
    eck_operator_helm_version: "3.5.0"
  tasks:
    - name: Build a kind cluster (wait for control plane).
      ansible.builtin.command: >-
        kind create cluster
        --wait 300s
        --name molecule-test
        --kubeconfig {{ kubeconfig }}
      changed_when: true

    - name: "Add elastic helm repo"
      kubernetes.core.helm_repository:
        name: "elastic"
        repo_url: "https://helm.elastic.co"

    - name: "Install ECK operator"
      kubernetes.core.helm:
        name: "elastic-operator"
        namespace: "elastic-system"
        chart_ref: "elastic/eck-operator"
        chart_version: "{{ eck_operator_helm_version }}"
        create_namespace: true
        update_repo_cache: true
        wait: true

    - name: "Install Zammad"
      ansible.builtin.import_role:
        name: "zammad"
      vars:
        zammad_wait_install: false

        zammad_ingress_enabled: false
        zammad_secrets_autowizard_secret_key: "autowizardsecretkey"
        zammad_secrets_autowizard_secret_name: "autowizard-secret-name"

        zammad_secrets_elasticsearch_use_existing: false
        zammad_secrets_elasticsearch_secret_key: "elasticsecretkey"
        zammad_secrets_elasticsearch_secret_name: "elastic-secret-name"

        zammad_secrets_postgresql_use_existing: false
        zammad_secrets_postgresql_secret_key: "postgresqlsecretkey"
        zammad_secrets_postgresql_secret_name: "postgresql-secret-name"

        zammad_secrets_redis_use_existing: false
        zammad_secrets_redis_secret_key: "redissecretkey"
        zammad_secrets_redis_secret_name: "redis-secret-name"
        zammad_redis_password: "zammad"


        zammad_postgresql_password: "zammad_passwrd"
