---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: "Wait for 'headlamp' namespace to be removed."
      kubernetes.core.k8s_info:
        kind: Namespace
        name: "headlamp"
      register: namespace_headlamp
      until: namespace_headlamp.resources | length == 0
      retries: 30
      delay: 5

    - name: "Assert that 'headlamp' namespace is removed."
      ansible.builtin.assert:
        that: namespace_headlamp.resources | length == 0
        fail_msg: "Namespace 'headlamp' is still present."
