---
galaxy_info:
  description: "Install and configure ClamAV on kubernetes"
  role_name: "clamav"
  author: "Clément Hubert"

  license: "MLP2"

  min_ansible_version: "2.1"

  galaxy_tags:
    - "kubernetes"
    - "clamav"
    - "antivirus"
    - "security"

dependencies: []
