---
# cleanup tasks for mailcrab
- name: "Remove extra manifests"
  kubernetes.core.k8s:
    namespace: "{{ mailcrab_namespace }}"
    state: "absent"
    definition: "{{ mailcrab_manifest_to_remove }}"
  loop: "{{ mailcrab_extra_manifests }}"
  loop_control:
    loop_var: mailcrab_manifest_to_remove
  when: mailcrab_extra_manifests | length > 0

- name: "Uninstall Mailcrab helm package"
  kubernetes.core.helm:
    name: "{{ mailcrab_deployment_name }}"
    namespace: "{{ mailcrab_namespace }}"
    state: "absent"

- name: "Remove mailcrab secret for basic auth"
  kubernetes.core.k8s:
    definition:
      api_version: "v1"
      kind: "Secret"
      metadata:
        name: "{{ mailcrab_basic_auth_secret_name }}"
        namespace: "{{ mailcrab_namespace }}"
    state: "absent"

- name: "Delete mailcrab namespace"
  kubernetes.core.k8s:
    name: "{{ mailcrab_namespace }}"
    api_version: "v1"
    kind: "Namespace"
    state: "absent"
