---
- name: "Converge"
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    # bcrypt hash for "molecule-admin-password"
    kargo_api_admin_password_hash: "$2a$10$Zrpo7AbzKCS24M77eEHo/.0XAuLeRGEZAkPJBnDR9LdGGtfCYxg9q"
    kargo_api_admin_token_signing_key: "molecule-token-signing-key-32chars"
  tasks:
    - name: "Install Kargo"
      ansible.builtin.import_role:
        name: "kargo"
