---
- name: "Converge"
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    warpgate_enabled: false
  tasks:
    - name: "Remove Warpgate"
      ansible.builtin.import_role:
        name: "warpgate"
