---
galaxy_info:
  description: Install Headlamp Kubernetes dashboard
  role_name: headlamp
  author: Clément Hubert

  license: MLP2

  min_ansible_version: "2.1"

  galaxy_tags:
    - kubernetes
    - headlamp
    - dashboard
    - ui

dependencies: []
