---
external_secrets_helm_repo_name: "external-secrets"
external_secrets_helm_repo_url: "https://charts.external-secrets.io"
external_secrets_helm_chart_ref: "{{ external_secrets_helm_repo_name }}/external-secrets"
external_secrets_crds_to_upgrade:
  - "https://raw.githubusercontent.com/external-secrets/external-secrets/{{ external_secrets_crd_version }}/deploy/crds/bundle.yaml"
