---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: "Wait for 'atlantis' namespace to be removed."
      kubernetes.core.k8s_info:
        kind: Namespace
        name: "atlantis"
      register: namespace_atlantis
      until: namespace_atlantis.resources | length == 0
      retries: 30
      delay: 5
      changed_when: false

    - name: "Assert that 'atlantis' namespace is removed."
      ansible.builtin.assert:
        that: namespace_atlantis.resources | length == 0
        fail_msg: "Namespace 'atlantis' is still present."
