---
- name: "Converge"
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    kargo_enabled: false
  tasks:
    - name: "Remove Kargo"
      ansible.builtin.import_role:
        name: "kargo"
