---
name: Test roles

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "roles/**"
      - ".github/**"
      - devbox.json
      - devbox.lock
      - flake.nix
      - flake.lock
  pull_request:
    branches: [main]
    paths:
      - "roles/**"
      - ".github/**"
      - devbox.json
      - devbox.lock
      - flake.nix
      - flake.lock

jobs:
  argocd:
    uses: ./.github/workflows/test-role.yaml
    with:
      role_name: "argocd"
  atlantis:
    uses: ./.github/workflows/test-role.yaml
    with:
      role_name: "atlantis"
  clamav:
    uses: ./.github/workflows/test-role.yaml
    with:
      role_name: "clamav"
  gatus:
    uses: ./.github/workflows/test-role.yaml
    with:
      role_name: "gatus"
  gitlab_runner:
    uses: ./.github/workflows/test-role.yaml
    with:
      role_name: "gitlab_runner"
  headlamp:
    uses: ./.github/workflows/test-role.yaml
    with:
      role_name: "headlamp"
  mailcrab:
    uses: ./.github/workflows/test-role.yaml
    with:
      role_name: "mailcrab"
  oauth2_proxy:
    uses: ./.github/workflows/test-role.yaml
    with:
      role_name: "oauth2_proxy"
  warpgate:
    uses: ./.github/workflows/test-role.yaml
    with:
      role_name: "warpgate"
  zammad:
    uses: ./.github/workflows/test-role.yaml
    with:
      role_name: "zammad"
